image: tmaier/docker-compose:latest

variables:
  # When using dind service, we need to instruct docker, to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. docker:19.03.1 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03.1/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services.
  #
  # Note that if you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2376 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2376
  #
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - name: docker:19.03.1-dind

stages:
  - test

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up -d
#    - docker-compose -f docker-compose.test.yml exec -T app sh -c "python manage.py migrate"
    - docker-compose -f docker-compose.test.yml exec -T app sh -c "flake8"
    - docker-compose -f docker-compose.test.yml exec -T app sh -c "pytest --cov"
    - docker-compose -f docker-compose.test.yml down
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
